{{- if or .Values.priorityClass.enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
value: {{ .Values.priorityClass.value }}
globalDefault: false
description: "Pods using TopoLVM volumes should use this class."
---
{{- end }}
