# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: webhook-selfsign
  namespace: topolvm-system
spec:
  selfSigned: {}
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: webhook-ca
  namespace: topolvm-system
spec:
  secretName: webhook-ca
  duration: 87600h0m0s # 10y
  issuerRef:
    name: webhook-selfsign
  commonName: "ca.webhook.topolvm"
  isCA: true
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: webhook-ca
  namespace: topolvm-system
spec:
  ca:
    secretName: webhook-ca
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: mutatingwebhook
  namespace: topolvm-system
spec:
  secretName: mutatingwebhook
  duration: 8760h0m0s # 1y
  issuerRef:
    name: webhook-ca
  dnsNames:
  - controller
  - controller.topolvm-system
  - controller.topolvm-system.svc
