apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-hook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topolvm-system:topolvm-hook
rules:
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list","watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topolvm-system:topolvm-hook
subjects:
  - kind: ServiceAccount
    namespace: topolvm-system
    name: topolvm-hook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topolvm-system:topolvm-hook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: topolvm-system
  name: topolvm-hook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-hook
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-hook
    spec:
      securityContext:
        runAsUser:  10000
        runAsGroup: 10000
      serviceAccountName: topolvm-hook
      containers:
        - name: topolvm-hook
          image: quay.io/cybozu/topolvm:0.1.1
          command:
            - /topolvm-hook
            - --cert-dir=/certs
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8080
              scheme: HTTP
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: topolvm-hook-certs
---
apiVersion: v1
kind: Service
metadata:
  namespace: topolvm-system
  name: topolvm-hook
spec:
  selector:
    app.kubernetes.io/name: topolvm-hook
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8443
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: topolvm-hook
  annotations:
    certmanager.k8s.io/inject-ca-from: topolvm-system/pod-mutatingwebhook
  labels:
    app.kubernetes.io/name: topolvm-hook
webhooks:
  - name: hook.topolvm.cybozu.com
    namespaceSelector:
      matchExpressions:
      - key: app.kubernetes.io/name
        operator: NotIn
        values: ["topolvm-system"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: topolvm-system
        name: topolvm-hook
        path: /mutate
    matchPolicy: Equivalent
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
