kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner
provisioner: topolvm.cybozu.com
parameters:
  "csi.storage.k8s.io/fstype": "xfs"
  "topolvm.cybozu.com/volume-group": "myvg1"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
