---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: psp:topolvm-scheduler
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topolvm-scheduler"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler:psp:topolvm-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:topolvm-scheduler
subjects:
- kind: ServiceAccount
  namespace: topolvm-system
  name: topolvm-scheduler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-scheduler
    spec:
      securityContext:
        runAsUser:  10000
        runAsGroup: 10000
      serviceAccountName: topolvm-scheduler
      containers:
        - name: topolvm-scheduler
          image: quay.io/cybozu/topolvm:0.4.8
          command:
            - /topolvm-scheduler
            - --listen=localhost:9251
            - --divisor=1
          livenessProbe:
            httpGet:
              host: localhost
              port: 9251
              path: /status
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
