apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - scheduler.yaml
images:
  - name: quay.io/topolvm/topolvm-with-sidecar
    newTag: 0.8.1
configMapGenerator:
  - name: scheduler-options
    namespace: topolvm-system
    files:
      - scheduler-options.yaml
