version: 2.1
commands:
  e2e-command:
    description: "e2e test"
    parameters:
      kubernetes-version:
        type: string
        default: ""
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export GOPATH=/home/circleci/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:/usr/local/go/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: setup golang
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.13.3
            curl -fsL https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | sudo tar xzf - -C /usr/local
      - run:
          name: Setup
          command: |
            make setup
            cd e2e
            if [ -n "<<parameters.kubernetes-version>>" ]; then
              OPT="TEST_KUBERNETES_VERSION=<<parameters.kubernetes-version>>"
            fi
            make ${OPT} setup
      - run:
          name: Run test
          command: |
            cd e2e
            make start-lvmd
            if [ -n "<<parameters.kubernetes-version>>" ]; then
              OPT="TEST_KUBERNETES_VERSION=<<parameters.kubernetes-version>>"
            fi
            make ${OPT} test

jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
      - checkout
      - run: make setup SUDO=""
      - run: make test
      - run: make build
      - persist_to_workspace:
          root: build
          paths: ["*"]
  image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run: cp -a /tmp/workspace build
      - setup_remote_docker
      - run: docker build -t quay.io/cybozu/topolvm:latest .
      - run:
          name: Push docker image to Quay.io
          command: |
            if [ "$CIRCLE_TAG" = "" ]; then exit 0; fi
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/topolvm:latest quay.io/cybozu/topolvm:$TAG
            docker push quay.io/cybozu/topolvm:$TAG
            if echo $TAG | grep -q -e - ; then
                echo ===== Skip pushing branch tags for pre-release $TAG =====
                exit 0
            fi
            BRANCH=$(echo $TAG | cut -d "." -f 1-2)
            docker tag quay.io/cybozu/topolvm:latest quay.io/cybozu/topolvm:$BRANCH
            docker push quay.io/cybozu/topolvm:$BRANCH
  publish-github-release:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: tar czf lvmd-${CIRCLE_TAG#v}.tar.gz -C ./artifacts lvmd
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_TAG} lvmd-*.tar.gz
  test-node:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/work
    steps:
      - checkout
      - run:
          name: install lvm
          command: |
            while true; do
                if sudo apt-get update; then
                    break
                fi
                sleep 1
            done
            sudo apt-get -y install --no-install-recommends lvm2
      - run:
          name: setup golang
          command: |
            sudo rm -rf /usr/local/go
            GO_VERSION=1.13.3
            curl -fsL https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | sudo tar xzf - -C /usr/local
      - run:
          name: run tests
          command: sudo env "GO111MODULE=on" "CIRCLECI=${CIRCLECI}" "CIRCLECI_EXECUTOR=machine" /usr/local/go/bin/go test -mod=vendor -race -v ./lvmd ./driver ./filesystem
  e2e-k8s-v1_15:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/work
    steps:
      - checkout
      - e2e-command:
          kubernetes-version: "1.15"
  e2e-k8s-v1_14:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/work
    steps:
      - checkout
      - e2e-command:
          kubernetes-version: "1.14"

workflows:
  version: 2
  main:
    jobs:
      - build
      - image:
          requires:
            - build
      - test-node
      - e2e-k8s-v1_15
      - e2e-k8s-v1_14
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
