apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - controller.yaml
  - mutatingwebhooks.yaml
  - namespace.yaml
  - node.yaml
  - provisioner.yaml
  - psp.yaml
  - scheduler.yaml
