apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd.yaml
  - controller.yaml
  - mutatingwebhooks.yaml
  - namespace.yaml
  - node.yaml
  - provisioner.yaml
  - psp.yaml
  - scheduler.yaml
configMapGenerator:
  - name: scheduler-options
    namespace: topolvm-system
    files:
      - scheduler-options.yaml
imageTags:
  - name: quay.io/cybozu/topolvm
    newTag: 0.5.0-rc.1
