image:
  repository: topolvm
  tag: dev
  pullPolicy: Never

controller:
  replicaCount: 1
  storageCapacityTracking:
    enabled: true
  securityContext:
    enabled: false
  # sanity test requires that the controller mounts this hostPath to communicate with it
  volumes:
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/topolvm.io/controller
        type: DirectoryOrCreate

scheduler:
  enabled: false

lvmd:
  socketName: /tmp/topolvm/daemonset_lvmd/lvmd.sock
  deviceClasses:
    - name: "ssd"
      volume-group: "node-myvg1"
      default: true
      spare-gb: 1
    - name: "hdd1"
      volume-group: "node-myvg2"
      spare-gb: 1
    - name: "hdd2"
      volume-group: "node-myvg3"
      spare-gb: 1
    - name: "raid"
      volume-group: "node-myvg4"
      spare-gb: 1
      lvcreate-options:
        - "--type=raid1"

node:
  lvmdSocket: /tmp/topolvm/daemonset_lvmd/lvmd.sock

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        topolvm.io/device-class: "ssd"

webhook:
  podMutatingWebhook:
    enabled: false

podSecurityPolicy:
  create: false

cert-manager:
  enabled: true
