image:
  repository: topolvm
  tag: dev
  pullPolicy: Never

controller:
  replicaCount: 1
  securityContext:
    enabled: false
  # sanity test requires that the controller mounts this hostPath to communicate with it
  volumes:
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/topolvm.io/controller
        type: DirectoryOrCreate

node:
  lvmdEmbedded: true

lvmd:
  managed: false
  deviceClasses:
    - name: "ssd"
      volume-group: "node-myvg1"
      default: true
      spare-gb: 1
    - name: "hdd1"
      volume-group: "node-myvg2"
      spare-gb: 1
    - name: "hdd2"
      volume-group: "node-myvg3"
      spare-gb: 1
    - name: "raid"
      volume-group: "node-myvg4"
      spare-gb: 1
      lvcreate-options:
        - "--type=raid1"
    - name: "thin"
      volume-group: "node-myvg5"
      type: thin
      thin-pool:
        name: "pool0"
        overprovision-ratio: 5.0
    - name: "raid1"
      volume-group: "node-myvg6"
      spare-gb: 1
  lvcreateOptionClasses:
    - name: "raid1"
      options:
        - "--type=raid1"

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        topolvm.io/device-class: "ssd"
  - name: topolvm-provisioner-thin
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        topolvm.io/device-class: "thin"

cert-manager:
  enabled: true
