image:
  repository: topolvm
  tag: dev
  pullPolicy: Never

controller:
  replicaCount: 1
  storageCapacityTracking:
    enabled: true
  securityContext:
    enabled: false
  nodeSelector:
    kubernetes.io/hostname: topolvm-e2e-worker
  # sanity test requires that the controller mounts this hostPath to communicate with it
  volumes:
    - name: socket-dir
      hostPath:
        path: /var/lib/kubelet/plugins/topolvm.cybozu.com/controller
        type: DirectoryOrCreate

scheduler:
  enabled: false

lvmd:
  managed: false

node:
  lvmdSocket: /tmp/topolvm/lvmd.sock

storageClasses:
  - name: topolvm-provisioner
    storageClass:
      fsType: xfs
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        topolvm.cybozu.com/device-class: "ssd"

webhook:
  podMutatingWebhook:
    enabled: false

podSecurityPolicy:
  create: false

cert-manager:
  enabled: true
