apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - ../common/storageclass.yaml
  - ../common/controller.yaml
  - ../common/node.yaml
  - mutatingwebhooks.yaml
resources:
  - ../../../../deploy/manifests/overlays/storage-capacity
  - ../../base
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - ../common/kustomizeconfig.yaml
secretGenerator:
- name: mutatingwebhook
  namespace: topolvm-system
  files:
  - ca.crt=../../../certs/cert.pem
  - tls.crt=../../../certs/cert.pem
  - tls.key=../../../certs/key.pem
  type: "Opaque"
vars:
  - name: TLSCERT
    objref:
      kind: Secret
      version: v1
      name: mutatingwebhook
    fieldref:
      fieldpath: data[ca.crt]
