{{- if or (.Values.lvmd.managed) (.Values.node.lvmdEmbedded) }}
  {{ $global := . }}
  {{- $lvmds := concat ( list .Values.lvmd ) .Values.lvmd.additionalConfigs }}
  {{- range $lvmdidx, $lvmd := $lvmds }}
    {{/* Undo the "." rewritten by the range block */}}
    {{- with $global }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd-{{ $lvmdidx }}
  namespace: {{ .Release.Namespace }}
  labels:
    idx: {{ $lvmdidx | quote}}
    {{- include "topolvm.labels" . | nindent 4 }}
data:
  lvmd.yaml: |
    {{- if not .Values.node.lvmdEmbedded }}
    socket-name: {{ default .Values.lvmd.socketName $lvmd.socketName }}
    {{- end }}
    {{- if $lvmd.deviceClasses }}
    device-classes: {{ toYaml $lvmd.deviceClasses | nindent 6 }}
    {{- end }}
    {{- if $lvmd.lvcreateOptionClasses }}
    lvcreate-option-classes: {{ toYaml $lvmd.lvcreateOptionClasses | nindent 6 }}
    {{- end }}
    {{- with $lvmd.additionalLVMDYamlContent }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
