{{- if .Values.lvmd.managed }}
  {{ $global := . }}
  {{- $lvmds := concat ( list .Values.lvmd ) .Values.lvmd.additionalConfigs }}
  {{- range $lvmdidx, $lvmd := $lvmds }}
    {{/* Undo the "." rewritten by the range block */}}
    {{- with $global }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd-{{ $lvmdidx }}
  namespace: {{ .Release.Namespace }}
  labels:
    idx: {{ $lvmdidx | quote }}
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  {{- with .Values.lvmd.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      idx: {{ $lvmdidx | quote }}
      app.kubernetes.io/component: lvmd
      {{- include "topolvm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        idx: {{ $lvmdidx | quote }}
        app.kubernetes.io/component: lvmd
        {{- include "topolvm.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/lvmd/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.lvmd.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "topolvm.fullname" . }}-lvmd
      hostPID: true
      containers:
        - name: lvmd
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - /lvmd
            - --container
          {{- with .Values.lvmd.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.lvmd.env }}
          env:
          {{- toYaml .Values.lvmd.env | nindent 10 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /lvmd
                - health
            initialDelaySeconds: 10
            timeoutSeconds: 3
          {{- with .Values.resources.lvmd }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/topolvm
            {{- if .Values.lvmd.volumeMounts }}
            {{- toYaml .Values.lvmd.volumeMounts | nindent 12 }}
            {{- else }}
            - name: lvmd-socket-dir
              mountPath: {{ dir .Values.lvmd.socketName }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "topolvm.fullname" . }}-lvmd-{{ $lvmdidx }}
        {{- if .Values.lvmd.volumes }}
        {{- toYaml .Values.lvmd.volumes | nindent 8 }}
        {{- else }}
        - name: lvmd-socket-dir
          hostPath:
            path: {{ dir .Values.lvmd.socketName }}
            type: DirectoryOrCreate
        {{- end }}
      {{- with $lvmd.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $lvmd.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
