{{- if .Values.lvmd.managed }}
  {{ $global := . }}
  {{- $lvmds := concat ( list .Values.lvmd ) .Values.lvmd.additionalConfigs }}
  {{- range $lvmdidx, $lvmd := $lvmds }}
    {{/* Undo the "." rewritten by the range block */}}
    {{- with $global }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "topolvm.fullname" . }}-lvmd-{{ $lvmdidx }}
  namespace: {{ .Release.Namespace }}
  labels:
    idx: {{ $lvmdidx | quote }}
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  {{- with .Values.lvmd.updateStrategy }}
  updateStrategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      idx: {{ $lvmdidx | quote }}
      app.kubernetes.io/name: topolvm-lvmd
  template:
    metadata:
      labels:
        idx: {{ $lvmdidx | quote }}
        app.kubernetes.io/name: topolvm-lvmd
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/lvmd/configmap.yaml") . | sha256sum }}
        {{- if and .Values.node.metrics.enabled .Values.node.metrics.annotations }}
        {{- toYaml .Values.node.metrics.annotations | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.lvmd.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ template "topolvm.fullname" . }}-lvmd
      hostPID: true
      containers:
        - name: lvmd
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          securityContext:
            privileged: true
          command:
            - /lvmd
            - --container
          {{- with .Values.lvmd.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/topolvm
            {{- if .Values.lvmd.volumeMounts }}
            {{- toYaml .Values.lvmd.volumeMounts | nindent 12 }}
            {{- else}}
            - name: lvmd-socket-dir
              mountPath: {{ dir .Values.lvmd.socketName }}
            {{- end}}
      volumes:
        - name: config
          configMap:
            name: {{ template "topolvm.fullname" . }}-lvmd-{{ $lvmdidx }}
        {{- if .Values.lvmd.volumes }}
        {{- toYaml .Values.lvmd.volumes | nindent 8 }}
        {{- else }}
        - name: lvmd-socket-dir
          hostPath:
            path: {{ dir .Values.lvmd.socketName }}
            type: DirectoryOrCreate
        {{- end }}
      {{- with $lvmd.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $lvmd.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
---
    {{- end }}
  {{- end }}
{{- end }}
