{{ if .Values.scheduler.enabled }}
  {{ if eq (lower .Values.scheduler.type) "deployment" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "topolvm.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scheduler.service.type }}
  selector:
    app.kubernetes.io/name: {{ template "topolvm.fullname" . }}-scheduler
  ports:
    - protocol: TCP
      port: {{ .Values.scheduler.options.listen.port }}
      {{- with .Values.scheduler.service.nodePort}}
      nodePort: {{ . }}
      {{- end }}
---
  {{ end }}
{{ end }}
