{{- if .Values.podSecurityPolicy.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:{{ template "topolvm.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topolvm-scheduler"]
---
{{- end }}
