{{- if .Values.podSecurityPolicy.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "topolvm.fullname" . }}-scheduler:psp:{{ template "topolvm.fullname" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:{{ template "topolvm.fullname" . }}-scheduler
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ template "topolvm.fullname" . }}-scheduler
---
{{- end }}
