apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "topolvm.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "topolvm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  {{- with .Values.controller.minReadySeconds }}
  minReadySeconds: {{ . }}
  {{- end }}
  {{- with .Values.controller.updateStrategy }}
  strategy: {{ toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      {{ include "topolvm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        {{ include "topolvm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.controller.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if .Values.controller.securityContext.enabled }}
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      serviceAccountName: {{ template "topolvm.fullname" . }}-controller
      containers:
        - name: topolvm-controller
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          command:
            - /topolvm-controller
            - --cert-dir=/certs
            {{- if .Values.controller.nodeFinalize.skipped }}
            - --skip-node-finalize
            {{- end }}
          ports:
            - containerPort: 9443
              name: webhook
              protocol: TCP
            - containerPort: 9808
              name: healthz
              protocol: TCP
            - containerPort: 8081
              name: readyz
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: readyz
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          {{- with .Values.controller.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm
            - name: certs
              mountPath: /certs

        - name: csi-provisioner
          {{- if .Values.image.csi.csiProvisioner }}
          image: {{ .Values.image.csi.csiProvisioner }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /csi-provisioner
            - --csi-address=/run/topolvm/csi-topolvm.sock
            - --feature-gates=Topology=true
            - --leader-election
            - --leader-election-namespace={{ .Release.Namespace }}
            {{- with .Values.controller.storageCapacityTracking.enabled }}
            - --enable-capacity
            - --capacity-ownerref-level=2
            {{- end }}
          {{- with .Values.controller.storageCapacityTracking.enabled }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm

        - name: csi-resizer
          {{- if .Values.image.csi.csiResizer }}
          image: {{ .Values.image.csi.csiResizer }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /csi-resizer
            - --csi-address=/run/topolvm/csi-topolvm.sock
            - --leader-election
            - --leader-election-namespace={{ .Release.Namespace }}
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm

         {{- if .Values.snapshot.enabled }}
        - name: csi-snapshotter
          {{- if .Values.image.csi.csiSnapshotter }}
          image: {{ .Values.image.csi.csiSnapshotter }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /csi-snapshotter
            - --csi-address=/run/topolvm/csi-topolvm.sock
            - --leader-election
            - --leader-election-namespace={{ .Release.Namespace }}
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm
        {{- end }}

        - name: liveness-probe
          {{- if .Values.image.csi.livenessProbe }}
          image: {{ .Values.image.csi.livenessProbe }}
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          {{- end }}
          {{- with .Values.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          command:
            - /livenessprobe
            - --csi-address=/run/topolvm/csi-topolvm.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /run/topolvm

      volumes:
        - name: certs
          secret:
            secretName: {{ template "topolvm.fullname" . }}-mutatingwebhook
        {{- with .Values.controller.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if ne .Values.controller.affinity "" }}
      affinity: {{ tpl .Values.controller.affinity . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
