kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: host-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-immediate
provisioner: topolvm.io
volumeBindingMode: Immediate
parameters:
  "topolvm.io/device-class": "ssd"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner2
provisioner: topolvm.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  "topolvm.io/device-class": "hdd1"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner3
provisioner: topolvm.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  "topolvm.io/device-class": "hdd2"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-default
provisioner: topolvm.io
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-mount-option
provisioner: topolvm.io
parameters:
  "csi.storage.k8s.io/fstype": "ext4"
  "topolvm.io/device-class": "ssd"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - debug
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-not-found-device
provisioner: topolvm.io
parameters:
  "topolvm.io/device-class": "not-found-device"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-raid
provisioner: topolvm.io
parameters:
  "topolvm.io/device-class": "raid"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topolvm-provisioner-raid1
provisioner: topolvm.io
parameters:
  "topolvm.io/device-class": "raid1"
  "topolvm.io/lvcreate-option-class": "raid1"
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: topolvm-provisioner-thin
driver: topolvm.io
deletionPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: host-local
  local:
    path: /tmp/e2etest1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - topolvm-e2e-control-plane
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: host-local
  local:
    path: /tmp/e2etest2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - topolvm-e2e-control-plane
