---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: psp:topolvm-lvmd
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topolvm-lvmd"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd:psp:topolvm-lvmd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:topolvm-lvmd
subjects:
- kind: ServiceAccount
  namespace: topolvm-system
  name: topolvm-lvmd
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
data:
  lvmd.yaml: |
    socket-name: /tmp/topolvm/lvmd_lvmd/lvmd.sock
    device-classes:
      - name: "ssd"
        volume-group: "node-myvg1"
        default: true
        spare-gb: 1
      - name: "hdd1"
        volume-group: "node-myvg2"
        spare-gb: 1
      - name: "hdd2"
        volume-group: "node-myvg3"
        spare-gb: 1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: topolvm-lvmd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topolvm-lvmd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topolvm-lvmd
    spec:
      serviceAccountName: topolvm-lvmd
      hostPID: true
      containers:
        - name: lvmd
          image: topolvm:dev
          imagePullPolicy: Never
          securityContext:
            privileged: true
          command:
            - /lvmd
            - --container
          volumeMounts:
            - name: lvmd-socket-dir
              mountPath: /tmp/topolvm/lvmd_lvmd
            - name: config
              mountPath: /etc/topolvm
      volumes:
        - name: config
          configMap:
            name: topolvm-lvmd
        - name: lvmd-socket-dir
          hostPath:
            path: /tmp/topolvm/lvmd_lvmd
            type: DirectoryOrCreate
