apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topolvm-system
  name: node
spec:
  template:
    spec:
      containers:
        - name: topolvm-node
          image: topolvm:dev
          imagePullPolicy: Never
          volumeMounts:
            - name: device-dir
              mountPath: /dev

        - name: csi-registrar
          image: topolvm:dev
          imagePullPolicy: Never

        - name: liveness-probe
          image: topolvm:dev
          imagePullPolicy: Never

      volumes:
        - name: lvmd-socket-dir
          hostPath:
            path: /tmp/topolvm/lvmd_lvmd
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
