{{ if .Values.useLegacy }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: logicalvolumes.topolvm.cybozu.com
spec:
  group: topolvm.cybozu.com
  names:
    kind: LogicalVolume
    listKind: LogicalVolumeList
    plural: logicalvolumes
    singular: logicalvolume
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: LogicalVolume is the Schema for the logicalvolumes API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: LogicalVolumeSpec defines the desired state of LogicalVolume
            properties:
              accessType:
                description: |-
                  'accessType' specifies how the user intends to consume the snapshot logical volume.
                  Set to "ro" when creating a snapshot and to "rw" when restoring a snapshot or creating a clone.
                  This field is populated only when LogicalVolume has a source.
                type: string
              deviceClass:
                type: string
              lvcreateOptionClass:
                type: string
              name:
                type: string
              nodeName:
                type: string
              size:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              source:
                description: |-
                  'source' specifies the logicalvolume name of the source; if present.
                  This field is populated only when LogicalVolume has a source.
                type: string
            required:
            - name
            - nodeName
            - size
            type: object
          status:
            description: LogicalVolumeStatus defines the observed state of LogicalVolume
            properties:
              code:
                description: |-
                  A Code is a status code defined according to the [gRPC documentation].

                  Only the codes defined as consts in this package are valid codes. Do not use
                  other code values.  Behavior of other codes is implementation-specific and
                  interoperability between implementations is not guaranteed.

                  [gRPC documentation]: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
                format: int32
                type: integer
              currentSize:
                anyOf:
                - type: integer
                - type: string
                pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                x-kubernetes-int-or-string: true
              message:
                type: string
              onlineSnapshot:
                properties:
                  completionTime:
                    description: CompletionTime is when the backup finished (success
                      or failure)
                    format: date-time
                    type: string
                  error:
                    description: Error provides structured failure info if the snapshot
                      failed
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                    type: object
                  message:
                    description: Message provides a short description of the snapshotâ€™s
                      state
                    type: string
                  phase:
                    description: Phase represents the current phase of the snapshot
                    type: string
                  progress:
                    description: Progress reports how much data has been backed up
                    properties:
                      bytesDone:
                        format: int64
                        type: integer
                      percentage:
                        description: Percentage can be calculated by controller or
                          client (UploadedBytes / TotalBytes * 100)
                        type: string
                      totalBytes:
                        format: int64
                        type: integer
                    type: object
                  retryCount:
                    description: RetryCount represents how many times this snapshot
                      operation has retried (for controller logic)
                    type: integer
                  snapshotID:
                    description: SnapshotID is the unique Restic snapshot identifier
                    type: string
                  startTime:
                    description: StartTime is when the backup process began
                    format: date-time
                    type: string
                  url:
                    description: URL is the Restic repository URL where the snapshot
                      is stored
                    type: string
                  version:
                    description: Version keeps track of restic binary or backup engine
                      version used
                    type: string
                type: object
              volumeID:
                description: |-
                  INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
                  Important: Run "make" to regenerate code after modifying this file
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

{{ end }}
