name: "e2e-k8s"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  build:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: cache e2e sidecar binaries
        uses: actions/cache@v4
        with:
          path: |
            test/e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk', 'versions.mk') }}
          restore-keys: |
            e2e-sidecars-
      - run: make -C test/e2e setup
      - run: make -C test/e2e topolvm.img
      - uses: actions/cache/save@v4
        with:
          path: |
            bin
            test/e2e/bin
            test/e2e/topolvm.img
          key: e2e-cache-${{ github.sha }}

  default:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      test_scheduler_extender_type: "daemonset"
      test_legacy: "false"

  scheduler-manifest:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      test_scheduler_extender_type: "deployment"
      test_legacy: "false"

  use-legacy:
    needs: build
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      test_scheduler_extender_type: "deployment"
      test_legacy: "true"
