name: "e2e-k8s-daemonset-lvmd"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"
jobs:
  e2e-k8s-daemonset-lvmd:
    name: "e2e-k8s-daemonset-lvmd"
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        kubernetes_versions: ["1.26.3", "1.25.8", "1.24.12"]
    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_versions }}
      STORAGE_CAPACITY: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-
      - name: cache e2e sidecar binaries
        uses: actions/cache@v3
        with:
          path: |
            e2e/tmpbin
          key: e2e-sidecars-${{ hashFiles('csi-sidecars.mk') }}
          restore-keys: |
            e2e-sidecars-
      - name: install dependencies of minikube
        run: |
          # These tools are required to use minikube for Kubernetes v1.24+

          # For CNI plugins, see https://github.com/Mirantis/cri-dockerd/blob/v0.2.6/README.md#important
          CNI_PLUGINS_VERSION="v1.2.0"
          curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/${CNI_PLUGINS_VERSION}/cni-plugins-linux-amd64-${CNI_PLUGINS_VERSION}.tgz
          sudo mkdir -p /opt/cni/bin
          sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz

          # Install cri-docker
          CRI_DOCKERD_VERSION="v0.3.1"
          curl -L -o cri-dockerd.deb https://github.com/Mirantis/cri-dockerd/releases/download/${CRI_DOCKERD_VERSION}/cri-dockerd_${CRI_DOCKERD_VERSION#v}.3-0.ubuntu-focal_amd64.deb
          sudo dpkg -i cri-dockerd.deb

          CRICTL_VERSION="v1.27.0"
          curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz --output crictl-${CRICTL_VERSION}-linux-amd64.tar.gz
          sudo tar zxvf crictl-$CRICTL_VERSION-linux-amd64.tar.gz -C /usr/local/bin
      - run: make -C e2e daemonset-lvmd/create-vg
      - run: make -C e2e daemonset-lvmd/setup-minikube
      - run: make -C e2e daemonset-lvmd/launch-minikube
      - run: make -C e2e daemonset-lvmd/test
