name: "Lint Charts"

on:
  pull_request:
    paths:
      - "charts/**"
      - "ct.yaml"

jobs:
  lint:
    runs-on: "ubuntu-22.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: "Setup Tools"
        run: |
          make tools

      - name: "Run helm-docs"
        run: ./bin/helm-docs && git diff --no-patch --exit-code

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.7.0

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml
