name: "Lint and Test Charts"

on:
  pull_request:
    paths:
      - "charts/**"
      - "ct.yaml"

jobs:
  lint-test:
    runs-on: "ubuntu-18.04"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Setup Go"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: cache go dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: go-${{ hashFiles('go.sum', 'Makefile') }}
          restore-keys: |
            go-

      - name: "Setup Tools"
        run: |
          make -C e2e setup

      - name: "Run helm-docs"
        run: ./bin/helm-docs && git diff --no-patch --exit-code

      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "Set up chart-testing"
        uses: helm/chart-testing-action@v2.2.0

      - name: "Run chart-testing (list-changed)"
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: "Run chart-testing (lint)"
        run: ct lint --config ct.yaml

      - name: "Setup kind"
        run: |
          make -C e2e daemonset-lvmd/create-vg
          make -C e2e daemonset-lvmd/setup-minikube
          make -C e2e daemonset-lvmd/update-minikube-setting
          make -C e2e prepare-namespace

      - name: "Apply cert-manager CRDs"
        run: kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.7.0/cert-manager.crds.yaml

      - name: "Run chart-testing (install)"
        run: ct install --config ct.yaml
