name: "Main"
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  build:
    name: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make setup
      - run: make check-uncommitted
      - run: make build-topolvm GOARCH=s390x
        name: "Build TopoLVM for s390x architecture"
      - run: make groupname-test
      # use sudo to test root required operations
      - run: sudo make test

  build-images:
    name: "build-images"
    uses: ./.github/workflows/build-images.yaml

  container-structure-test:
    name: "container-structure-test"
    needs: build
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: true
      matrix:
        image:
          - "normal"
          - "with-sidecar"
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make install-container-structure-test
      - run: make image-${{ matrix.image }}
      - run: make container-structure-test STRUCTURE_TEST_TARGET=${{ matrix.image }}

  example:
    if:  startsWith(github.head_ref, 'bump-chart-')
    name: "example"
    runs-on: "ubuntu-22.04"
    defaults:
      run:
        working-directory: "example"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: make setup
      - run: make run
