name: Main
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup
      - run: make check-uncommitted
      - run: make test
      - run: sudo -E env PATH=${PATH} go test -race -v ./lvmd ./driver ./filesystem
      - run: make image
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_kubernetes_target: [current, prev, prev2]
        test_scheduler_manifest: [daemonset, deployment]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
      TEST_SCHEDULER_MANIFEST: ${{ matrix.test_scheduler_manifest }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make -C e2e setup
      - run: make -C e2e start-lvmd
      - run: make -C e2e test
  e2e-k8s-daemonset-lvmd-test:
    name: e2e-k8s-daemonset-lvmd-test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        test_kubernetes_target: [current, prev, prev2]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make -C e2e setup
      - run: make -C e2e daemonset-lvmd/create-vg
      - run: make -C e2e daemonset-lvmd/setup-minikube
      - run: make -C e2e daemonset-lvmd/update-minikube-setting
      - run: make -C e2e daemonset-lvmd/test
  example:
    name: example
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: make setup
      - run: make run BUILD_IMAGE=true
