name: Main
on:
  pull_request:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make setup
      - run: make check-uncommitted
      - run: make test
      - run: sudo -E env PATH=${PATH} go test -mod=vendor -race -v ./lvmd ./driver ./filesystem
      - run: make image
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        test_kubernetes_target: [current, prev, prev2]
        test_scheduler_manifest: [daemonset, deployment]
    env:
      TEST_KUBERNETES_TARGET: ${{ matrix.test_kubernetes_target }}
      TEST_SCHEDULER_MANIFEST: ${{ matrix.test_scheduler_manifest }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make setup
      - run: make -C e2e setup
      - run: make -C e2e start-lvmd
      - run: make -C e2e test
  example:
    name: example
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: example
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make setup
      - run: make run
